version: '3.8'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
     - db
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
     - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: