version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test_db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
     - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
  
  test_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=n0yhz
      - POSTGRES_PASSWORD=module11
      - POSTGRES_TEST_DB=test_db
    ports:
     - "7654:7654"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: